// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_Learning.Data;

#nullable disable

namespace WebAPI_Learning.Migrations
{
    [DbContext(typeof(CollegeDBContext))]
    partial class CollegeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_Learning.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kapsi",
                            DOB = new DateTime(2004, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "janvi@gmail.com",
                            StudentName = "Janvi"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nagpur",
                            DOB = new DateTime(2008, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hasari@gmail.com",
                            StudentName = "Hasari"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kapsi",
                            DOB = new DateTime(2004, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jay@gmail.com",
                            StudentName = "Jay"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bhandara",
                            DOB = new DateTime(2005, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa@gmail.com",
                            StudentName = "Lisa"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Bhandara",
                            DOB = new DateTime(2005, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rosy@gmail.com",
                            StudentName = "Rosy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
